dataDirName: '/tmp'

database:

  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the JDBC URL
#  url: jdbc:mysql://localhost:3306/depositauth_development
  url: jdbc:mysql://mysql.lib.virginia.edu:3306/depositauth_development

  # the username
#  user: root
  user: depauth_dev

  # the password
#  password:
  password: yp3EHea3

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* DepositAuth Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false