dataDirName: '/this/that/the/other'

#database:
#  driverClass: org.h2.Driver
#  user: sa
#  password:
#  url: jdbc:h2:./persondb
#  properties:
#    charSet: UTF-8
#  maxWaitForConnection: 1s
#  validationQuery: "/* DepositAuth Health Check */ SELECT 1"
#  minSize: 8
#  maxSize: 32
#  checkConnectionWhileIdle: false
#  evictionInterval: 10s
#  minIdleTime: 1 minute

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/depositauth_development

  # the username
  user: root

  # the password
  password:

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* DepositAuth Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  #checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  #closeConnectionIfIdleFor: 1 minute